# version:     "0026--06-Sep-2022"
copyright:   "2022"
author:      "edutjie"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/edutjie/os222/"
myloglink:   "/TXT/mylog.txt"
tarballlink: "https://os.vlsm.org/Log/edutjie.tar.bz2.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]